[package]
name = "patoka"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.29", features = ["rwh_06"] }
ash = { version = "0.38.0", features = ["linked", "debug", "std"] }
ash-window = "0.13.0"
vk-mem = "0.4.0"
